package jsons;

public class Jsons {
	public static String patBody() {
		return "{\r\n" + "  \"name\": [\r\n" + "    {\r\n" + "      \"use\": \"official\",\r\n"
				+ "      \"text\": \"Flanders,Ned,Hans\",\r\n" + "      \"family\": \"Flanders\",\r\n"
				+ "      \"given\": [\r\n" + "        \"Ned\",\r\n" + "        \"Hans\"\r\n" + "      ],\r\n"
				+ "      \"period\": {\r\n" + "        \"start\": \"2018-11-06\"\r\n" + "      }\r\n" + "    }\r\n"
				+ "  ],\r\n" + "  \"gender\": \"FEMALE\",\r\n" + "  \"birthDate\": \"2000-12-31\",\r\n"
				+ "  \"maritalStatus\": {\r\n" + "    \"coding\": [\r\n" + "      {\r\n"
				+ "        \"system\": \"http://hl7.org/fhir/v3/MaritalStatus\",\r\n" + "        \"code\": \"m\",\r\n"
				+ "        \"display\": \"Married\"\r\n" + "      }\r\n" + "    ],\r\n"
				+ "    \"text\": \"Married\"\r\n" + "  },\r\n" + "  \"communication\": [\r\n" + "    {\r\n"
				+ "      \"language\": {\r\n" + "        \"coding\": [\r\n" + "          {\r\n"
				+ "            \"system\": \"urn:ietf:bcp:47\",\r\n" + "            \"code\": \"PL\",\r\n"
				+ "            \"display\": \"Polish\"\r\n" + "          }\r\n" + "        ],\r\n"
				+ "        \"text\": \"Polish\"\r\n" + "      },\r\n" + "      \"preferred\": true\r\n" + "    }\r\n"
				+ "  ],\r\n" + "  \"telecom\": [\r\n" + "    {\r\n" + "      \"extension\": [\r\n" + "        {\r\n"
				+ "          \"valueBoolean\": false,\r\n"
				+ "          \"url\": \"http://hl7.org/fhir/StructureDefinition/iso21090-preferred\"\r\n"
				+ "        }\r\n" + "      ],\r\n" + "      \"system\":  \"phone\",\r\n"
				+ "      \"value\": \"(111) 111 1111\",\r\n" + "      \"use\":  \"home\"\r\n" + "      \r\n"
				+ "    },\r\n" + "    {\r\n" + "      \"system\": \"email\",\r\n"
				+ "      \"value\": \"name@test.com\"\r\n" + "    }\r\n" + "  ],\r\n" + "  \"address\": [\r\n"
				+ "        {\r\n" + "            \"use\": \"home\",\r\n" + "            \"type\": \"postal\",\r\n"
				+ "            \"text\": \"89 Parkway,Philadelphia,USA,19111\",\r\n" + "            \"line\": [\r\n"
				+ "                \"29 Parkway Street\"\r\n" + "            ],\r\n"
				+ "            \"city\": \"Philadelphia\",\r\n" + "            \"district\": \"Philadelphia\",\r\n"
				+ "            \"state\": \"PA\",\r\n" + "            \"postalCode\": \"19111\",\r\n"
				+ "            \"country\": \"USA\",\r\n" + "            \"period\": {\r\n"
				+ "                \"start\": \"2018-10-11\"\r\n" + "            }\r\n" + "        }\r\n" + "    ]\r\n"
				+ "  \r\n" + "}";
	}

	public static String encBody(String persNo) {
		return "{\r\n" + "    \"resourceType\": \"Encounter\",\r\n" + "    \"class\": \"inpatient\",\r\n"
				+ "    \"status\": \"planned\",\r\n" + "    \"type\": [\r\n" + "        {\r\n"
				+ "            \"text\": \"Inpatient\"\r\n" + "        }\r\n" + "    ],\r\n" + "    \"period\": {\r\n"
				+ "        \"start\": \"2019-01-01T01:02:00 -04:00\"\r\n" + "    },\r\n" + "    \"extension\": [\r\n"
				+ "        {\r\n"
				+ "            \"url\": \"http://[CORRECT FHIR SERVER]/StructureDefinition/encounter-ProvidingOrganization\",\r\n"
				+ "            \"valueReference\": {\r\n" + "                \"reference\": \"organization/626\",\r\n"
				+ "                \"display\": \"Automation IP\"\r\n" + "            }\r\n" + "        },\r\n"
				+ "        {\r\n"
				+ "            \"url\": \"http://[CORRECT FHIR SERVER]/StructureDefinition/encounter-userData\",\r\n"
				+ "            \"extension\": [\r\n" + "                {\r\n"
				+ "                    \"valueString\": \"Temporary\",\r\n"
				+ "                    \"url\": \"http://srfdev0132.dm50.dev.smed.net/sf-dvlp0132/soarian/StructureDefinition/patient-userData_AutoEncDropDown\"\r\n"
				+ "                },\r\n" + "                {\r\n"
				+ "                    \"valueString\": \"5.25\",\r\n"
				+ "                    \"url\": \"http://srfdev0132.dm50.dev.smed.net/sf-dvlp0132/soarian/StructureDefinition/patient-userData_AutoEncCurrency\"\r\n"
				+ "                },\r\n" + "                {\r\n"
				+ "                    \"valueString\": \"2018-12-01\",\r\n"
				+ "                    \"url\": \"http://srfdev0132.dm50.dev.smed.net/sf-dvlp0132/soarian/StructureDefinition/patient-userData_AutoEncDate\"\r\n"
				+ "                },\r\n" + "                {\r\n"
				+ "                    \"valueString\": \"true\",\r\n"
				+ "                    \"url\": \"http://srfdev0132.dm50.dev.smed.net/sf-dvlp0132/soarian/StructureDefinition/patient-userData_AutoEncCheckbox\"\r\n"
				+ "                },\r\n" + "                {\r\n"
				+ "                    \"valueString\": \"10\",\r\n"
				+ "                    \"url\": \"http://srfdev0132.dm50.dev.smed.net/sf-dvlp0132/soarian/StructureDefinition/patient-userData_AutoEncNumber10To999\"\r\n"
				+ "                },\r\n" + "                {\r\n"
				+ "                    \"valueString\": \"9.9999\",\r\n"
				+ "                    \"url\": \"http://srfdev0132.dm50.dev.smed.net/sf-dvlp0132/soarian/StructureDefinition/patient-userData_AutoEncNumber1Decimal0To10\"\r\n"
				+ "                },\r\n" + "                {\r\n"
				+ "                    \"valueString\": \"AAAAA\",\r\n"
				+ "                    \"url\": \"http://srfdev0132.dm50.dev.smed.net/sf-dvlp0132/soarian/StructureDefinition/patient-userData_AutoEncTextbox\"\r\n"
				+ "                },\r\n" + "                {\r\n"
				+ "                    \"valueString\": \"2019-01-01 01:02:00\",\r\n"
				+ "                    \"url\": \"http://srfdev0132.dm50.dev.smed.net/sf-dvlp0132/soarian/StructureDefinition/patient-userData_AutoEncDateTime\"\r\n"
				+ "                },\r\n" + "                {\r\n"
				+ "                    \"valueString\": \"01:45:59\",\r\n"
				+ "                    \"url\": \"http://srfdev0132.dm50.dev.smed.net/sf-dvlp0132/soarian/StructureDefinition/patient-userData_AutoEncTime\"\r\n"
				+ "                }\r\n" + "            ]\r\n" + "        }\r\n" + "    ],\r\n"
				+ "    \"location\": [\r\n" + "        {\r\n" + "            \"location\": {\r\n"
				+ "                \"display\": \"Automation RO\",\r\n"
				+ "                \"reference\": \"location/892\"\r\n" + "            }\r\n" + "        }\r\n"
				+ "    ],\r\n" + "    \"subject\": {\r\n" + "        \"reference\": \"patient/" + persNo +"\"\r\n"
				+ "    }\r\n" + "}";
	}
}
